import type { CATQuestion } from '@/types'

export const SAMPLE_QUESTIONS: CATQuestion[] = [
  {
    id: 'q1',
    text: 'Choose the correct word: "She ___ to the office every day."',
    options: ['go', 'goes', 'going', 'gone'],
    correctIndex: 1,
    cefrLevel: 'A1',
    difficulty: 1,
  },
  {
    id: 'q2',
    text: 'What does "Hello" mean?',
    options: ['Goodbye', 'Thanks', 'Hi', 'Please'],
    correctIndex: 2,
    cefrLevel: 'A1',
    difficulty: 1,
  },
  {
    id: 'q3',
    text: 'Complete the sentence: "I ___ a student at this university."',
    options: ['am', 'is', 'are', 'be'],
    correctIndex: 0,
    cefrLevel: 'A1',
    difficulty: 2,
  },
  {
    id: 'q4',
    text: 'Which sentence is correct?',
    options: [
      'He don\'t like coffee.',
      'He doesn\'t likes coffee.',
      'He doesn\'t like coffee.',
      'He not like coffee.',
    ],
    correctIndex: 2,
    cefrLevel: 'A2',
    difficulty: 3,
  },
  {
    id: 'q5',
    text: 'Choose the correct past tense: "Yesterday I ___ a great movie."',
    options: ['watch', 'watches', 'watched', 'watching'],
    correctIndex: 2,
    cefrLevel: 'A2',
    difficulty: 3,
  },
  {
    id: 'q6',
    text: 'Which word best completes the sentence: "The meeting has been ___ to next week."',
    options: ['postponed', 'postulated', 'proposed', 'promoted'],
    correctIndex: 0,
    cefrLevel: 'B1',
    difficulty: 5,
  },
  {
    id: 'q7',
    text: 'Select the correct conditional: "If I ___ more time, I would learn another language."',
    options: ['have', 'had', 'would have', 'having'],
    correctIndex: 1,
    cefrLevel: 'B1',
    difficulty: 5,
  },
  {
    id: 'q8',
    text: 'Which phrase is most appropriate in a professional email?',
    options: [
      'Hey, what\'s up?',
      'I am writing to inquire about...',
      'Wanna talk about the project?',
      'Just checking in lol',
    ],
    correctIndex: 1,
    cefrLevel: 'B1',
    difficulty: 5,
    sector: 'business',
  },
  {
    id: 'q9',
    text: 'Complete with the correct relative clause: "The software ___ we use daily needs updating."',
    options: ['who', 'which', 'what', 'whose'],
    correctIndex: 1,
    cefrLevel: 'B2',
    difficulty: 6,
  },
  {
    id: 'q10',
    text: 'What does "scalability" mean in a tech context?',
    options: [
      'The ability to fix bugs quickly',
      'The capacity to handle growing amounts of work',
      'The process of deploying code',
      'A type of database structure',
    ],
    correctIndex: 1,
    cefrLevel: 'B2',
    difficulty: 6,
    sector: 'tech',
  },
  {
    id: 'q11',
    text: 'Identify the error: "The data was analyzed and their results were presented."',
    options: [
      'No error',
      '"data" should be plural verb',
      '"their" should be "its"',
      '"presented" should be "presenting"',
    ],
    correctIndex: 2,
    cefrLevel: 'B2',
    difficulty: 7,
  },
  {
    id: 'q12',
    text: 'Which best describes a "P&L statement"?',
    options: [
      'A project management tool',
      'A profit and loss financial report',
      'A programming language guide',
      'A personnel listing',
    ],
    correctIndex: 1,
    cefrLevel: 'B2',
    difficulty: 7,
    sector: 'business',
  },
  {
    id: 'q13',
    text: 'Choose the correct passive construction: "The algorithm ___ to improve accuracy."',
    options: [
      'has been refined',
      'have been refined',
      'was refining',
      'refined',
    ],
    correctIndex: 0,
    cefrLevel: 'C1',
    difficulty: 8,
    sector: 'tech',
  },
  {
    id: 'q14',
    text: 'What does "regression analysis" primarily help determine?',
    options: [
      'The relationship between variables',
      'The speed of an algorithm',
      'The accuracy of a classifier',
      'The size of a dataset',
    ],
    correctIndex: 0,
    cefrLevel: 'C1',
    difficulty: 8,
    sector: 'data',
  },
  {
    id: 'q15',
    text: 'Select the most precise academic expression: "The study ___ that prior interventions were insufficient."',
    options: [
      'showed',
      'demonstrated conclusively',
      'kind of showed',
      'basically proved',
    ],
    correctIndex: 1,
    cefrLevel: 'C1',
    difficulty: 9,
  },
  {
    id: 'q16',
    text: 'Which sentence demonstrates the most sophisticated use of hedging language?',
    options: [
      'This will definitely solve the problem.',
      'The evidence suggests this may potentially mitigate the issue.',
      'Maybe this could work or maybe not.',
      'This is probably the solution.',
    ],
    correctIndex: 1,
    cefrLevel: 'C2',
    difficulty: 10,
  },
  {
    id: 'q17',
    text: 'Identify the rhetorical device: "We must act not for ourselves, but for those who cannot yet speak — our children and grandchildren."',
    options: ['Anaphora', 'Prolepsis', 'Chiasmus', 'Litotes'],
    correctIndex: 1,
    cefrLevel: 'C2',
    difficulty: 10,
  },
  {
    id: 'q18',
    text: 'In agile methodology, what is a "sprint retrospective"?',
    options: [
      'A review of the product backlog',
      'A team reflection on process improvement after a sprint',
      'A presentation to stakeholders',
      'A planning session for the next sprint',
    ],
    correctIndex: 1,
    cefrLevel: 'C1',
    difficulty: 8,
    sector: 'tech',
  },
  {
    id: 'q19',
    text: 'Complete: "The merger, ___ took many by surprise, reshaped the entire industry landscape."',
    options: ['that', 'which', 'what', 'who'],
    correctIndex: 1,
    cefrLevel: 'C1',
    difficulty: 9,
    sector: 'business',
  },
  {
    id: 'q20',
    text: 'What is "feature engineering" in machine learning?',
    options: [
      'Designing new software features',
      'The process of transforming raw data into informative model inputs',
      'Engineering the model architecture',
      'Testing model performance on new data',
    ],
    correctIndex: 1,
    cefrLevel: 'C1',
    difficulty: 8,
    sector: 'data',
  },
]
